name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Secrets/variables'ı ENV'e yaz
      - name: Prepare credentials and env
        shell: bash
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > "${RUNNER_TEMP}/gcp.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=${RUNNER_TEMP}/gcp.json" >> $GITHUB_ENV
          echo "SERPER_API_KEY=${{ secrets.SERPER_API_KEY }}" >> $GITHUB_ENV
          echo "GOOGLE_CLOUD_PROJECT=${{ vars.GOOGLE_CLOUD_PROJECT }}" >> $GITHUB_ENV
          echo "GOOGLE_CLOUD_REGION=${{ vars.GOOGLE_CLOUD_REGION }}" >> $GITHUB_ENV

      - run: npm ci
      - run: npm run build
